name: movie_db_flutter_bloc_clean
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bloc_test: ^9.1.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.5
  ez_cache:
    path: ./core/ez_cache
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations: # Add this line
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  import_sorter: ^4.6.0
  injectable: ^2.1.0
  intl: ^0.17.0
  mockito: ^5.3.2
  retrofit: ^3.3.1
  shared_preferences: ^2.0.16

dev_dependencies:
  build_runner:
  flutter_flavorizr: ^2.1.5
  flutter_gen_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  injectable_generator:
  json_serializable: ^6.5.4
  retrofit_generator:
  shimmer: ^2.0.0

flutter_gen:
  output: lib/src/core/utils/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/colors/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: NeueMontreal
      fonts:
        - asset: assets/fonts/NeueMontreal-Light.otf
          weight: 300
        - asset: assets/fonts/NeueMontreal-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/NeueMontreal-Regular.otf
        - asset: assets/fonts/NeueMontreal-Italic.otf
          style: italic
        - asset: assets/fonts/NeueMontreal-Bold.otf
          weight: 700
        - asset: assets/fonts/NeueMontreal-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/NeueMontreal-Medium.otf
          weight: 500
        - asset: assets/fonts/NeueMontreal-MediumItalic.otf
          weight: 500
          style: italic

flavorizr:
  flavors:
    dev:
      app:
        icon: "assets/images/splash.jpg"
        name: "MovieDB DEV"

      android:
        applicationId: "com.movie.db.dev"

      ios:
        bundleId: "com.movie.db.dev"

    prod:
      app:
        icon: "assets/images/splash.jpg"
        name: "MovieDB"

      android:
        applicationId: "com.movie.db"

      ios:
        bundleId: "com.movie.db"

    stag:
      app:
        icon: "assets/images/splash.jpg"
        name: "MovieDB staging"

      android:
        applicationId: "com.movie.db.stag"

      ios:
        bundleId: "com.movie.db.stag"

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash.jpg
  ios: true
  android: true
